### ISSUE TITLE
首要通知

### ISSUE THREAD

**Issue by cabbagelol** [cabbagelol/bfban-app-mobile#2]

**Comment by SoraKasvgano** [comment]
啊这，下载地址页的话，建议除了 国内软件商店上架 还可以 增加 蓝奏云，下载速度真的很快。

**Comment by SoraKasvgano** [comment]
emmm 还一个建议，就是 如果自己举报过的人 信息更新了，或者 审查状态变更了 是否需要 新增 APP通知推送功能。

不知道 是否需要对毛毛@mygoare 的后端 进行相关修改

**Comment by mygoare** [comment]
> emmm 还一个建议，就是 如果自己举报过的人 信息更新了，或者 审查状态变更了 是否需要 新增 APP通知推送功能。
> 
> 
> 
> 不知道 是否需要对毛毛@mygoare 的后端 进行相关修改

我可以调用推送接口，前提是 要有推送的功能实现……
我不是很懂手机推送

**Comment by cabbagelol** [comment]
推送可以实现，但实时的推送限制非常多，如果改为定时推送就简单；这里我有一个办法。提供一个“每日推送”默认时间12点，可以修改时间。

还有这种需求性，请开一个新的Issues :D
