### ISSUE TITLE
小米mix2s  使用问题

### ISSUE THREAD

**Issue by Am6zingDavid** [cabbagelol/bfban-app-mobile#3]
miui12 app版本 0.0.3
外挂公示 点不进去 一直是BFBAN Legion of Ban Coalition

**Comment by cabbagelol** [comment]
感谢反馈:D @Am6zingDavid 
你能提供根据详细截图和描述么，列如系统信息、操作录屏之类的。对于我来说很大的帮助。

另外非常感谢你在这里提出第一个Issues。

**Comment by cabbagelol** [comment]
我已经在0.0.4尝试修复-> https://github.com/cabbagelol/bfbanApp/releases/tag/0.0.4-beta
